### ISSUE TITLE
Ambiguous options and parameters in CLI mode

### ISSUE THREAD

**Issue by pankajgodbole** [sinKettu/cruster#15]
Expected - Cruster runs in CLI mode
Actual - Cruster throws an error about project not being provided to the CLI command.

Description - 

In CLI mode issuing the below command results in an error -

Command - 
`cargo run cli http show 2`

Result - 
`Error in Cruster CLI: Cruster CLI cannot work without project specified`

The README is not clear on what a "project" is and how to provide it to the command.

**Comment by sinKettu** [comment]
Hello!
I would recommend you to read documentation carefully.
First of all, I can see that you copied command from README, so if you will look at "CLI" paragraph, you will notice the following words:

> CLI works with data, stored in dump or interactive modes, so it is required to provide a path to project to use CLI (via cmd argument or config).

So, "project" is the data collected with proxy (not only, actually), like in ZAP, for example.
You can specify a path to project with command line argument - `cruster -P <path> clie http show 2` or with config. You can find [here](https://github.com/sinKettu/cruster/blob/master/docs/Cruster%20YAML%20Config%20Format.md) how the config is built.

So, to use CLI you need to collect proxy data in project via TUI or dump modes.
