### ISSUE TITLE
docker installation error 

### ISSUE THREAD

**Issue by nsk** [sinKettu/cruster#16]
pi@Chester:~/cruster $ sudo docker build . -f docker/Dockerfile -t local/cruster
[+] Building 163.1s (13/14)                                                                                                           docker:default
 => [internal] load build definition from Dockerfile                                                                                            0.0s
 => => transferring dockerfile: 1.04kB                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                 1.2s
 => [internal] load .dockerignore                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                 0.0s
 => [ 1/10] FROM docker.io/library/ubuntu:22.04@sha256:e9569c25505f33ff72e88b2990887c9dcf230f23259da296eb814fc2b41af999                         0.0s
 => [internal] load build context                                                                                                               0.0s
 => => transferring context: 320.48kB                                                                                                           0.0s
 => CACHED [ 2/10] RUN mkdir /opt/cruster     && useradd -u 4242 --shell /bin/bash --home /opt/cruster cruster     && chown -R cruster /opt/cr  0.0s
 => CACHED [ 3/10] RUN apt-get update     && apt-get install --no-install-recommends -y         build-essential         git         ca-certifi  0.0s
 => CACHED [ 4/10] WORKDIR /opt/cruster                                                                                                         0.0s
 => CACHED [ 5/10] RUN curl --proto '=https' --tlsv1.2 -sSf -o rustup.sh https://sh.rustup.rs     && sh rustup.sh -y     && mkdir cruster-src   0.0s
 => CACHED [ 6/10] COPY src cruster-src/src                                                                                                     0.0s
 => CACHED [ 7/10] COPY Cargo.toml cruster-src/                                                                                                 0.0s
 => CACHED [ 8/10] COPY Cargo.lock cruster-src/                                                                                                 0.0s
 => ERROR [ 9/10] RUN cargo install     --path ./cruster-src                                                                                  161.7s
------                                                                                                                                               
 > [ 9/10] RUN cargo install     --path ./cruster-src:                                                                                               
0.671   Installing cruster v0.7.2 (/opt/cruster/cruster-src)                                                                                         
0.760     Updating crates.io index                                                                                                                   
5.359  Downloading crates ...                                                                                                                        
5.724   Downloaded waker-fn v1.1.1                                                                                                                   
5.755   Downloaded bytes v1.5.0
5.778   Downloaded bytecount v0.6.7
5.804   Downloaded wayland-sys v0.29.5
5.826   Downloaded colorchoice v1.0.0
5.842   Downloaded openssl-probe v0.1.5
5.854   Downloaded x11-clipboard v0.7.1
5.897   Downloaded wayland-commons v0.29.5
5.912   Downloaded autocfg v1.1.0
5.928   Downloaded num v0.4.1
5.950   Downloaded anstyle-query v1.0.2
5.970   Downloaded triomphe v0.1.11
5.989   Downloaded anstyle-parse v0.2.3
6.002   Downloaded bitflags v2.4.2
6.027   Downloaded enumset_derive v0.8.1
6.041   Downloaded webpki v0.22.4
6.096   Downloaded base64 v0.13.1
6.139   Downloaded darling_core v0.20.5
6.220   Downloaded tinyvec_macros v0.1.1
6.238   Downloaded form_urlencoded v1.2.1
6.247   Downloaded num-conv v0.1.0
6.258   Downloaded gethostname v0.2.3
6.266   Downloaded clap v4.4.18
6.319   Downloaded wayland-protocols v0.29.5
6.388   Downloaded rustls-native-certs v0.6.3
6.406   Downloaded asn1-rs-derive v0.4.0
6.416   Downloaded time-core v0.1.2
6.425   Downloaded pem v1.1.1
6.435   Downloaded once_cell v1.19.0
6.448   Downloaded errno v0.3.8
6.456   Downloaded digest v0.10.7
6.472   Downloaded futures-executor v0.3.30
6.484   Downloaded futures-io v0.3.30
6.492   Downloaded quote v1.0.35
6.517   Downloaded sync_wrapper v0.1.2
6.526   Downloaded cursive_core v0.3.7
6.593   Downloaded utf8parse v0.2.1
6.600   Downloaded num-iter v0.1.43
6.606   Downloaded strsim v0.10.0
6.613   Downloaded tokio-macros v2.2.0
6.619   Downloaded utf-8 v0.7.6
6.624   Downloaded untrusted v0.9.0
6.638   Downloaded tokio-native-tls v0.3.1
6.653   Downloaded signal-hook-registry v1.4.1
6.663   Downloaded cursive_buffered_backend v0.6.1
6.674   Downloaded try-lock v0.2.5
6.683   Downloaded unsafe-any-ors v1.0.0
6.692   Downloaded openssl-sys v0.9.99
6.734   Downloaded mime v0.3.17
6.763   Downloaded uuid v1.7.0
6.806   Downloaded hyper-tls v0.5.0
6.832   Downloaded lock_api v0.4.11
6.847   Downloaded displaydoc v0.2.4
6.867   Downloaded hyper-rustls v0.24.2
6.880   Downloaded cursive_table_view v0.14.0
6.891   Downloaded shellexpand v2.1.2
6.902   Downloaded num-complex v0.4.4
6.916   Downloaded smallvec v1.13.1
6.933   Downloaded unicode-bidi v0.3.15
6.954   Downloaded rustls-pemfile v1.0.4
6.975   Downloaded native-tls v0.2.11
6.996   Downloaded synstructure v0.12.6
7.006   Downloaded brotli-decompressor v2.5.1
7.057   Downloaded tempfile v3.9.0
7.077   Downloaded unicode-xid v0.2.4
7.089   Downloaded unicode-segmentation v1.10.1
7.117   Downloaded serde_yaml v0.8.26
7.138   Downloaded cursive v0.20.0
7.180   Downloaded ident_case v1.0.1
7.189   Downloaded spin v0.9.8
7.209   Downloaded unicode-normalization v0.1.22
7.238   Downloaded zstd v0.13.0
7.261   Downloaded wayland-scanner v0.29.5
7.273   Downloaded lazy_static v1.4.0
7.285   Downloaded moka v0.11.3
7.347   Downloaded xml-rs v0.8.19
7.374   Downloaded log4rs v1.2.0
7.405   Downloaded indexmap v2.2.2
7.438   Downloaded asn1-rs v0.5.2
7.489   Downloaded rand v0.8.5
7.519   Downloaded openssl v0.10.63
7.589   Downloaded time v0.3.34
7.623   Downloaded rustls v0.20.9
7.710   Downloaded rustls-webpki v0.101.7
7.819   Downloaded vcpkg v0.2.15
8.169   Downloaded webpki-roots v0.22.6
8.198   Downloaded rustix v0.37.27
8.353   Downloaded zstd-sys v2.0.9+zstd.1.5.5
8.483   Downloaded linux-raw-sys v0.4.13
8.747   Downloaded brotli v3.4.0
8.899   Downloaded encoding_rs v0.8.33
9.054   Downloaded ring v0.16.20
9.377   Downloaded ring v0.17.7
9.652   Downloaded libc v0.2.153
9.772   Downloaded linux-raw-sys v0.3.8
9.859   Downloaded idna v0.5.0
9.889   Downloaded syn v2.0.48
9.931   Downloaded syn v1.0.109
9.974   Downloaded tokio v1.36.0
10.36   Downloaded regex-automata v0.4.5
10.44   Downloaded rustix v0.38.31
10.54   Downloaded regex-syntax v0.8.2
10.57   Downloaded zerocopy v0.7.32
10.64   Downloaded webpki-roots v0.25.4
10.66   Downloaded rustls v0.21.10
10.71   Downloaded nix v0.24.3
10.75   Downloaded hyper v0.14.28
10.78   Downloaded bstr v1.9.0
10.83   Downloaded x11rb-protocol v0.10.0
10.88   Downloaded regex-automata v0.1.10
10.91   Downloaded tokio-util v0.7.10
10.93   Downloaded async-compression v0.4.6
10.97   Downloaded mio v0.8.10
10.99   Downloaded regex v1.10.3
11.05   Downloaded tracing v0.1.40
11.07   Downloaded http v0.2.11
11.08   Downloaded hashbrown v0.12.3
11.10   Downloaded flate2 v1.0.28
11.12   Downloaded num-bigint v0.4.4
11.14   Downloaded bstr v0.2.17
11.18   Downloaded serde_json v1.0.113
11.21   Downloaded iana-time-zone v0.1.60
11.22   Downloaded log v0.4.20
11.23   Downloaded tracing-core v0.1.32
11.24   Downloaded unicode-width v0.1.11
11.25   Downloaded serde_derive v1.0.196
11.26   Downloaded indexmap v1.9.3
11.27   Downloaded h2 v0.3.24
11.30   Downloaded petgraph v0.6.4
11.36   Downloaded socket2 v0.5.5
11.37   Downloaded x509-parser v0.14.0
11.39   Downloaded destructure_traitobject v0.2.0
11.40   Downloaded chrono v0.4.33
11.43   Downloaded memoffset v0.6.5
11.43   Downloaded typenum v1.17.0
11.44   Downloaded io-lifetimes v1.0.11
11.45   Downloaded yaml-rust v0.4.5
11.47   Downloaded unicode-ident v1.0.12
11.48   Downloaded tinyvec v1.6.0
11.49   Downloaded socket2 v0.4.10
11.50   Downloaded signal-hook v0.3.17
11.51   Downloaded futures-util v0.3.30
11.56   Downloaded reqwest v0.11.24
11.59   Downloaded pin-project v1.1.4
11.64   Downloaded minimal-lexical v0.2.1
11.66   Downloaded num-rational v0.4.1
11.67   Downloaded rcgen v0.10.0
11.68   Downloaded rustls-webpki v0.100.3
11.70   Downloaded hudsucker v0.20.0
11.72   Downloaded clap_builder v4.4.18
11.75   Downloaded tokio-rustls v0.23.4
11.75   Downloaded httparse v1.8.0
11.76   Downloaded futures v0.3.30
11.78   Downloaded tungstenite v0.19.0
11.79   Downloaded yasna v0.5.2
11.80   Downloaded webpki-roots v0.23.1
11.82   Downloaded url v2.5.0
11.83   Downloaded ipnet v2.9.0
11.84   Downloaded httpdate v1.0.3
11.84   Downloaded tokio-rustls v0.24.1
11.85   Downloaded tracing-attributes v0.1.27
11.86   Downloaded zstd-safe v7.0.0
11.87   Downloaded hyper-tungstenite v0.10.0
11.88   Downloaded tokio-tungstenite v0.19.0
11.88   Downloaded slab v0.4.9
11.89   Downloaded rand_core v0.6.4
11.90   Downloaded serde_urlencoded v0.7.1
11.90   Downloaded serde-value v0.7.0
11.91   Downloaded percent-encoding v2.3.1
11.91   Downloaded ordered-float v2.10.1
11.92   Downloaded untrusted v0.7.1
11.92   Downloaded futures-lite v1.13.0
11.93   Downloaded futures-channel v0.3.30
11.94   Downloaded async-trait v0.1.77
11.95   Downloaded rand_chacha v0.3.1
11.96   Downloaded quanta v0.11.1
11.97   Downloaded parking_lot v0.12.1
11.98   Downloaded xi-unicode v0.3.0
11.99   Downloaded x11rb v0.10.1
12.03   Downloaded thiserror-impl v1.0.56
12.03   Downloaded thiserror v1.0.56
12.06   Downloaded version_check v0.9.4
12.06   Downloaded cli-clipboard v0.4.0
12.07   Downloaded rusticata-macros v4.1.0
12.08   Downloaded oid-registry v0.6.1
12.08   Downloaded miniz_oxide v0.7.2
12.09   Downloaded stable_deref_trait v1.2.0
12.09   Downloaded thread-id v4.2.1
12.10   Downloaded signal-hook-mio v0.2.3
12.10   Downloaded futures-core v0.3.30
12.11   Downloaded fnv v1.0.7
12.11   Downloaded fastrand v2.0.1
12.12   Downloaded dirs-sys v0.3.7
12.13   Downloaded dirs v4.0.0
12.13   Downloaded itoa v1.0.10
12.14   Downloaded getrandom v0.2.12
12.15   Downloaded proc-macro2 v1.0.78
12.16   Downloaded polling v2.8.0
12.17   Downloaded num-traits v0.2.17
12.19   Downloaded ryu v1.0.16
12.20   Downloaded aho-corasick v1.1.2
12.22   Downloaded derivative v2.2.0
12.25   Downloaded crossbeam-channel v0.5.11
12.27   Downloaded typemap-ors v1.0.0
12.27   Downloaded spin v0.5.2
12.28   Downloaded sha1 v0.10.6
12.29   Downloaded http-body v0.4.6
12.29   Downloaded der-parser v8.2.0
12.31   Downloaded pin-project-lite v0.2.13
12.33   Downloaded pin-project-internal v1.1.4
12.34   Downloaded mime_guess v2.0.4
12.35   Downloaded scopeguard v1.2.0
12.35   Downloaded futures-macro v0.3.30
12.36   Downloaded num_threads v0.1.6
12.36   Downloaded tower-service v0.3.2
12.36   Downloaded powerfmt v0.2.0
12.37   Downloaded hashbrown v0.14.3
12.39   Downloaded crossterm v0.25.0
12.42   Downloaded num-integer v0.1.45
12.42   Downloaded cc v1.0.83
12.44   Downloaded arc-swap v1.6.0
12.45   Downloaded unicase v2.7.0
12.46   Downloaded asn1-rs-impl v0.1.0
12.46   Downloaded log-mdc v0.1.0
12.46   Downloaded want v0.3.1
12.47   Downloaded generic-array v0.14.7
12.47   Downloaded futures-task v0.3.30
12.48   Downloaded futures-sink v0.3.30
12.48   Downloaded ppv-lite86 v0.2.17
12.49   Downloaded pkg-config v0.3.29
12.49   Downloaded pin-utils v0.1.0
12.50   Downloaded num_cpus v1.16.0
12.51   Downloaded scheduled-thread-pool v0.2.7
12.52   Downloaded owning_ref v0.4.1
12.52   Downloaded os_pipe v1.1.5
12.53   Downloaded linked-hash-map v0.5.6
12.53   Downloaded time-macros v0.2.17
12.54   Downloaded fixedbitset v0.4.2
12.55   Downloaded event-listener v2.5.3
12.55   Downloaded downcast-rs v1.2.0
12.56   Downloaded nom v7.1.3
12.58   Downloaded foreign-types-shared v0.1.1
12.58   Downloaded foreign-types v0.3.2
12.59   Downloaded equivalent v1.0.1
12.59   Downloaded crypto-common v0.1.6
12.59   Downloaded base64 v0.21.7
12.61   Downloaded parking_lot_core v0.9.9
12.62   Downloaded serde v1.0.196
12.63   Downloaded sct v0.7.1
12.65   Downloaded memchr v2.7.1
12.67   Downloaded deranged v0.3.11
12.67   Downloaded data-encoding v2.5.0
12.68   Downloaded darling v0.20.5
12.69   Downloaded crossbeam-epoch v0.9.18
12.71   Downloaded cpufeatures v0.2.12
12.71   Downloaded concurrent-queue v2.4.0
12.72   Downloaded clap_lex v0.6.0
12.72   Downloaded cfg-if v1.0.0
12.73   Downloaded async-lock v2.8.0
12.74   Downloaded wayland-client v0.29.5
12.75   Downloaded derive-new v0.5.9
12.75   Downloaded darling_macro v0.20.5
12.75   Downloaded anyhow v1.0.79
12.77   Downloaded block-buffer v0.10.4
12.78   Downloaded bitflags v1.3.2
12.79   Downloaded anstream v0.6.11
12.80   Downloaded enumset v1.1.3
12.81   Downloaded crossbeam-utils v0.8.19
12.82   Downloaded byteorder v1.5.0
12.83   Downloaded alloc-no-stdlib v2.0.4
12.83   Downloaded adler v1.0.2
12.84   Downloaded enum-map v2.7.3
12.85   Downloaded crc32fast v1.3.2
12.86   Downloaded async-io v1.13.0
12.86   Downloaded parking v2.2.0
12.87   Downloaded jobserver v0.1.27
12.88   Downloaded hyper-rustls v0.23.2
12.89   Downloaded anstyle v1.0.5
12.89   Downloaded wl-clipboard-rs v0.7.0
12.90   Downloaded alloc-stdlib v0.2.2
12.91   Downloaded humantime v2.1.0
12.91   Downloaded tree_magic_mini v3.0.3
12.92   Downloaded tagptr v0.2.0
12.93   Downloaded enum-map-derive v0.17.0
12.93   Downloaded colored v2.1.0
12.94   Downloaded fastrand v1.9.0
12.94   Downloaded openssl-macros v0.1.1
12.95   Downloaded ahash v0.8.7
13.17    Compiling libc v0.2.153
13.17    Compiling proc-macro2 v1.0.78
13.17    Compiling unicode-ident v1.0.12
13.17    Compiling autocfg v1.1.0
13.53    Compiling cfg-if v1.0.0
16.02    Compiling serde v1.0.196
17.78    Compiling once_cell v1.19.0
19.45    Compiling memchr v2.7.1
22.38    Compiling quote v1.0.35
23.57    Compiling jobserver v0.1.27
24.89    Compiling syn v2.0.48
27.11    Compiling cc v1.0.83
27.37    Compiling pkg-config v0.3.29
30.68    Compiling smallvec v1.13.1
32.45    Compiling version_check v0.9.4
32.59    Compiling getrandom v0.2.12
34.22    Compiling itoa v1.0.10
34.77    Compiling lock_api v0.4.11
35.00    Compiling pin-project-lite v0.2.13
35.24    Compiling parking_lot_core v0.9.9
35.86    Compiling num-traits v0.2.17
36.42    Compiling scopeguard v1.2.0
39.24    Compiling signal-hook-registry v1.4.1
40.89    Compiling parking_lot v0.12.1
46.17    Compiling ring v0.17.7
49.60    Compiling bytes v1.5.0
50.27    Compiling futures-core v0.3.30
50.93    Compiling slab v0.4.9
51.71    Compiling syn v1.0.109
51.83    Compiling fnv v1.0.7
52.04    Compiling untrusted v0.9.0
52.51    Compiling spin v0.9.8
53.29    Compiling socket2 v0.5.5
53.35    Compiling num_cpus v1.16.0
58.18    Compiling futures-sink v0.3.30
58.54    Compiling futures-io v0.3.30
59.68    Compiling bitflags v1.3.2
59.85    Compiling thiserror v1.0.56
63.14    Compiling num-integer v0.1.45
63.78    Compiling futures-channel v0.3.30
64.15    Compiling ring v0.16.20
65.62    Compiling futures-task v0.3.30
66.48    Compiling hashbrown v0.14.3
68.08    Compiling crossbeam-utils v0.8.19
69.56    Compiling pin-utils v0.1.0
69.70    Compiling time-core v0.1.2
70.76    Compiling equivalent v1.0.1
70.94    Compiling powerfmt v0.2.0
72.85    Compiling num-conv v0.1.0
73.12    Compiling vcpkg v0.2.15
73.90    Compiling time-macros v0.2.17
78.86    Compiling serde_derive v1.0.196
79.46    Compiling tokio-macros v2.2.0
85.33    Compiling thiserror-impl v1.0.56
87.77    Compiling futures-macro v0.3.30
95.63    Compiling futures-util v0.3.30
97.21    Compiling openssl-sys v0.9.99
101.0    Compiling indexmap v2.2.2
109.0    Compiling deranged v0.3.11
125.3    Compiling num_threads v0.1.6
127.1    Compiling bitflags v2.4.2
129.1    Compiling lazy_static v1.4.0
129.4    Compiling time v0.3.34
136.0 error: failed to run custom build command for `openssl-sys v0.9.99`
136.0 
136.0 Caused by:
136.0   process didn't exit successfully: `/opt/cruster/cruster-src/target/release/build/openssl-sys-3b19c89f57f7658b/build-script-main` (exit status: 101)
136.0   --- stdout
136.0   cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
136.0   AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
136.0   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
136.0   OPENSSL_LIB_DIR unset
136.0   cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
136.0   AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
136.0   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
136.0   OPENSSL_INCLUDE_DIR unset
136.0   cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
136.0   AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
136.0   cargo:rerun-if-env-changed=OPENSSL_DIR
136.0   OPENSSL_DIR unset
136.0   cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
136.0   cargo:rerun-if-env-changed=PKG_CONFIG
136.0   cargo:rerun-if-env-changed=OPENSSL_STATIC
136.0   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
136.0   cargo:rerun-if-env-changed=OPENSSL_STATIC
136.0   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
136.0   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
136.0   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
136.0   run pkg_config fail: Could not run `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl`
136.0   The pkg-config command could not be found.
136.0 
136.0   Most likely, you need to install a pkg-config package for your OS.
136.0   Try `apt install pkg-config`, or `yum install pkg-config`,
136.0   or `pkg install pkg-config`, or `apk add pkgconfig` depending on your distribution.
136.0 
136.0   If you've already installed it, ensure the pkg-config command is one of the
136.0   directories in the PATH environment variable.
136.0 
136.0   If you did not expect this build to link to a pre-installed system library,
136.0   then check documentation of the openssl-sys crate for an option to
136.0   build the library from source, or disable features or dependencies
136.0   that require pkg-config.
136.0 
136.0   --- stderr
136.0   thread 'main' panicked at /opt/cruster/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.99/build/find_normal.rs:190:5:
136.0 
136.0 
136.0   Could not find directory of OpenSSL installation, and this `-sys` crate cannot
136.0   proceed without this knowledge. If OpenSSL is installed and this crate had
136.0   trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
136.0   compilation process.
136.0 
136.0   Make sure you also have the development packages of openssl installed.
136.0   For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
136.0 
136.0   If you're in a situation where you think the directory *should* be found
136.0   automatically, please open a bug at https://github.com/sfackler/rust-openssl
136.0   and include information about your system as well as this message.
136.0 
136.0   $HOST = aarch64-unknown-linux-gnu
136.0   $TARGET = aarch64-unknown-linux-gnu
136.0   openssl-sys = 0.9.99
136.0 
136.0 
136.0   It looks like you're compiling on Linux and also targeting Linux. Currently this
136.0   requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
136.0   could not be found. If you have OpenSSL installed you can likely fix this by
136.0   installing `pkg-config`.
136.0 
136.0 
136.0   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
136.0 warning: build failed, waiting for other jobs to finish...
160.1 error: failed to compile `cruster v0.7.2 (/opt/cruster/cruster-src)`, intermediate artifacts can be found at `/opt/cruster/cruster-src/target`.
160.1 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
------
Dockerfile:36
--------------------
  35 |     
  36 | >>> RUN cargo install \
  37 | >>>     --path ./cruster-src
  38 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo install     --path ./cruster-src" did not complete successfully: exit code: 101
pi@Chester:~/cruster $

**Comment by sinKettu** [comment]
Hello, @nsk !
Sorry for a waitinig.

You have two options:

- Downgrade repo version to [v0.7.1](https://github.com/sinKettu/cruster/releases/tag/v0.7.1) of Cruster.
- Use [Dockerfile-openssl-ncurses](https://github.com/sinKettu/cruster/blob/master/docker/Dockerfile-openssl-ncurses) file to build docker image.

In version `0.7.2` I have added an ability to use system installed certificates, but i did not notice that it requires OpenSSL, and that causes the problem. I'll fix it and improve Dockerfiles in version 0.8.0, which I'm working on now.

**Comment by nsk** [comment]
thx i try 0.7.1

**Comment by nsk** [comment]
hi , 

still having problems, I'm on a raspi 4b maybe the problem??

pi@Chester:~ $ cd cruster-0.7.1 && sudo docker build . -f docker/Dockerfile-openssl-ncurses -t local/cruster
[+] Building 22.1s (7/15)                                                                                                             docker:default
 => [internal] load build definition from Dockerfile-openssl-ncurses                                                                            0.0s
 => => transferring dockerfile: 1.36kB                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                 0.5s
 => [internal] load .dockerignore                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                 0.0s
 => [ 1/11] FROM docker.io/library/ubuntu:22.04@sha256:f9d633ff6640178c2d0525017174a688e2c1aef28f0a0130b26bd5554491f0da                         0.0s
 => [internal] load build context                                                                                                               0.1s
 => => transferring context: 319.39kB                                                                                                           0.0s
 => CACHED [ 2/11] RUN mkdir /opt/cruster     && useradd -u 4242 --shell /bin/bash --home /opt/cruster cruster     && chown -R cruster /opt/cr  0.0s
 => ERROR [ 3/11] RUN apt-get update     && apt-get install --no-install-recommends -y         locales=2.35-0ubuntu3.1     && locale-gen en_U  21.4s
------                                                                                                                                               
 > [ 3/11] RUN apt-get update     && apt-get install --no-install-recommends -y         locales=2.35-0ubuntu3.1     && locale-gen en_US.UTF-8:       
0.578 Get:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]                                                                            
0.824 Get:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]                                                                    
0.898 Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [109 kB]                                                                  
0.989 Get:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]                                                                   
1.127 Get:5 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages [1758 kB]
2.363 Get:6 http://ports.ubuntu.com/ubuntu-ports jammy/restricted arm64 Packages [24.2 kB]
2.394 Get:7 http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages [17.2 MB]
10.50 Get:8 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse arm64 Packages [224 kB]
10.64 Get:9 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted arm64 Packages [1301 kB]
11.35 Get:10 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [1532 kB]
11.95 Get:11 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse arm64 Packages [28.4 kB]
12.04 Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [1266 kB]
12.57 Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-backports/universe arm64 Packages [26.2 kB]
12.58 Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-backports/main arm64 Packages [49.9 kB]
12.61 Get:15 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted arm64 Packages [1270 kB]
13.02 Get:16 http://ports.ubuntu.com/ubuntu-ports jammy-security/multiverse arm64 Packages [24.0 kB]
13.04 Get:17 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages [1256 kB]
13.41 Get:18 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages [997 kB]
13.85 Fetched 27.6 MB in 13s (2066 kB/s)
13.85 Reading package lists...
16.27 Reading package lists...
18.58 Building dependency tree...
19.00 Reading state information...
19.02 Package locales is not available, but is referred to by another package.
19.02 This may mean that the package is missing, has been obsoleted, or
19.02 is only available from another source
19.02 
19.03 E: Version '2.35-0ubuntu3.1' for 'locales' was not found
------
Dockerfile-openssl-ncurses:9
--------------------
   8 |     # For ncurses
   9 | >>> RUN apt-get update \
  10 | >>>     && apt-get install --no-install-recommends -y \
  11 | >>>         locales=2.35-0ubuntu3.1 \
  12 | >>>     && locale-gen en_US.UTF-8
  13 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update     && apt-get install --no-install-recommends -y         locales=2.35-0ubuntu3.1     && locale-gen en_US.UTF-8" did not complete successfully: exit code: 100

**Comment by nsk** [comment]
hi, I solved the problem I did: 
sudo apt install rustup, 
then rustup update stable, 
the installation in 0.7.1 works under kali in wsl,
 I will now have to test on raspi

**Comment by nsk** [comment]
works fine
